### ISSUE TITLE
Consider displaying Core attributes as a group

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#1011]
I think if we're going to permit users to add core attributes to groups, we need to commit to treating them like an (immutable) group. That means displaying "**Core attributes**" with the same colored side border (maybe gray?) on the incident page and the incident creation flow, as if core attributes are just another group.

**Comment by noah-schechter** [comment]
I see the problem we run into here with ungrouped custom attributes—where to display them if not with the core attributes? 

I'm not sure what the best solution is here, but I stand by the initial concern with the fact that core attributes are \~floating freely\~ in the case that someone has grouped all of their other attributes.

**Comment by milesmcc** [comment]
Yeah I agree; the core attributes should not be freely floating. When I redesign the incident page, the core attributes will be integrated into other parts of the page, so this won't be an issue.

Two reasons I didn't do more with core attribute integration (into the main page) are that:

1. I didn't want to make many design changes too quickly
2. I wanted attribute grouping to be purely opt-in; people who want to keep using Atlos as they previously had will experience essentially no changes from this update.

I worry that further separating core attributes will make this update more disruptive for existing users?

**Comment by noah-schechter** [comment]
Understood, this makes sense. Resolving this.
