### ISSUE TITLE
Bulk upload 'Confirm information' buttons

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#104]
On failed bulk uploads, we provide a 'New Upload' button so the user can restart the upload process. Can we add the same button in the case of successful uploads, i.e. on the Confirm information page? This would give the user the opportunity to restart the process without having to navigate back to Adminland first.

We might have to rename this button so it successfully communicates that the current upload will be cancelled. Perhaps 'Restart upload?'

My lo-fi mockup (button locations would be switched, probably?): 
<img width="600" alt="Screen Shot 2022-06-23 at 23 50 04" src="https://user-images.githubusercontent.com/100018299/175479729-3408b55b-6e59-4c25-949b-20df64bf37c5.png">

**Comment by milesmcc** [comment]
Great idea.
