### ISSUE TITLE
Make source link optional

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#211]
For satellite imagery, there's not always a clear source link to provide. In these cases, we should provide an alternate, freeform text entry so investigators can still trace the provenance of media, even if it's not a URL.

**Comment by milesmcc** [comment]
Hmm. Is the satellite imagery publicly visible at all? Is it not possible to provide a link to Google Maps or something?

**Comment by noah-schechter** [comment]
In some cases, not really. There might be a preview, but for commercially-available imagery, something you might buy from Planet, I think researchers are buying from within the company's platform. Perhaps we end up deciding satellite imagery of this type is just out of scope, but I think it's worth thinking about how to incorporate it, as it can be valuable tool to augment eyewitness media.
