### ISSUE TITLE
Access to media in comments expires too fast

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#212]
Perhaps this is an intentional security measure, but when I stay on an incident page for a while (I haven't figured out the exact duration yet), and then try opening media from a comment in a new tab, I get an "Access Denied" XML message saying that the request expired. If you're able to manually change how long requests last, can we extend this? 

For context, simply refreshing the incident page solves the problem. 

<img width="824" alt="Screen Shot 2022-09-15 at 20 22 11" src="https://user-images.githubusercontent.com/100018299/190550270-6e3df78f-cdd3-43f9-8544-1d038a5d4faa.png">

**Comment by milesmcc** [comment]
How long do you think it should last? Maybe six hours? 24?

**Comment by noah-schechter** [comment]
I think six is sufficient.
