### ISSUE TITLE
The border of the location panel is misaligned when location is unset

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#213]
This is only an issue on staging.

<img width="411" alt="Screen Shot 2022-09-18 at 13 22 41" src="https://user-images.githubusercontent.com/100018299/190926814-2482d6ff-085b-44d6-8db7-e1d170301876.png">

**Comment by noah-schechter** [comment]
Unfortunately I'm still seeing this in staging: 

<img width="440" alt="Screen Shot 2022-09-19 at 10 44 54" src="https://user-images.githubusercontent.com/100018299/191080439-844962ad-b9e8-4ca0-983d-3128ac5b5b5b.png">

**Comment by milesmcc** [comment]
Nevermind, replicated in Safari. Fixed for real this time.

**Comment by milesmcc** [comment]
As an aside, very glad you're testing in Safari — I develop in Chrome and there are too many websites that don't work properly in Chrome.
