### ISSUE TITLE
Attribute changes fail immediately after manual media upload completes

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#215]
If I attempt to change an attribute (specifically Sensitivity or Status) immediately after uploading media, about 50% of the time, I won't be able to click through to the attribute edit modal. I'm sending a screen recording privately because GitHub can't handle the file size.

**Comment by milesmcc** [comment]
Should be fixed, deploying to staging now. Needs verification though.

**Comment by noah-schechter** [comment]
Wasn't able to recreate in staging with the newest deployment.
