### ISSUE TITLE
Limit text in More Info box to the Attributes panel

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#217]
The example for this includes Bellingcat data so I'll send this privately.

**Comment by milesmcc** [comment]
Should be fixed

**Comment by milesmcc** [comment]
Still kind of overflows, though. Good enough for now.

**Comment by milesmcc** [comment]
https://github.com/atlosdotorg/atlos/commit/e9563e664485b6f6b153a080f9ce2a9422353dbd
