### ISSUE TITLE
Security setting field disappears after users enter the user-facing description

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#221]
In the New Security Mode modal, after entering the user-facing description, the security setting field disappears, preventing admins from actually changing the security mode.

**Comment by noah-schechter** [comment]
It also disappears if a user edits the security mode itself.

https://user-images.githubusercontent.com/100018299/191412445-6bb7e8ee-52c5-42d1-8139-58380f73a96e.mov

**Comment by milesmcc** [comment]
Oh yeah I observed this and just kind of ignored it because it's an admin only page but you're totally right

**Comment by noah-schechter** [comment]
Yeah none of the issues I filed related to Security Mode are high priority because they're all essentially cosmetic changes to Adminland but I just wanted make sure we had this logged.
