### ISSUE TITLE
Do we need to require a user-facing description when changing Security Mode back to 'normal'?

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#224]
We currently require this. It doesn't really matter, because the description is never displayed, but something to consider changing.

**Comment by milesmcc** [comment]
Too much effort/complexity to make the input go away when the status is normal — I just updated the field description so it's clear that it's only shown when in a non-Normal mode.

**Comment by milesmcc** [comment]
Nevermind I see what you mean — no need to make the input disappear, but rather just make it optional. Done.
