### ISSUE TITLE
Guard Atlos rules link on incident creation page behind system prompt warning that you're going to leave Atlos 

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#254]
A la "Open the Atlos rules in a new tab? Your current incident won't be affected." 
Part of this change is also making the rules open in a new tab by default.

**Comment by milesmcc** [comment]
I don't think we should have a warning popup, since these are trustworthy links, and in general I think people find popups very annoying. Let's just open in a new tab.
