### ISSUE TITLE
Muted user in comment box causes Function Clause Error

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#267]
I think this may be because we permit muted users to move through the file upload process in the comment box, we just don't actually let them upload the media? 
<img width="710" alt="Screen Shot 2022-09-30 at 18 11 35" src="https://user-images.githubusercontent.com/100018299/193377390-4e3d2c37-cdee-47cf-bb28-123b952de8e9.png">

**Comment by milesmcc** [comment]
It's finally time to fix this one isn't it lol

**Comment by milesmcc** [comment]
Should be fixed
