### ISSUE TITLE
Fix z index issues for banners on graphic violence media

### ISSUE THREAD

**Issue by milesmcc** [atlosdotorg/atlos#311]
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/3037552/194796746-f4670d8e-f3de-4fe4-9250-1ea9af72a4d6.png">

**Comment by noah-schechter** [comment]
Closing this as a duplicate of #340.

**Comment by milesmcc** [comment]
Lol how many times can I notice this and not realize it's a dupe
