### ISSUE TITLE
Add some kind of activity dashboard (DAUs, etc)

### ISSUE THREAD

**Issue by milesmcc** [atlosdotorg/atlos#312]

**Comment by noah-schechter** [comment]
Some helpful metrics would be: DAUs; live users (so we know when it's reasonably safe to deploy); and some kind of incident math: daily new incidents, daily active incidents (incidents with updates), and/or daily incidents completed.

**Comment by noah-schechter** [comment]
Adding some more potentially-helpful data points:
- Total number of projects
- Some kind of metrics of social spread and sharing. I think it would be helpful to understand how and to what degree investigators are collaborating; short of a social graph (which we don't need or want), metrics on number of users per project could be helpful.

**Comment by noah-schechter** [comment]
I think we should make this a priority after media archival; it will be especially helpful as we onboard additional users.
