### ISSUE TITLE
Consider allowing editing directly within text cells of table view

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#315]
I think I'm against this, because the 'Update' button (rightly) makes Atlos feel more like something with traditional version control than continuous editing like Google Sheets. But I want to make sure we're considering this option before we add table view because the attribute editing window adds another layer of interaction that might be unexpected because it isn't present in Google Sheets or AirTable.

**Comment by milesmcc** [comment]
This would take an enormous amount of effort I think
