### ISSUE TITLE
Add integration (somehow) with search.ix5.org

### ISSUE THREAD

**Issue by milesmcc** [atlosdotorg/atlos#316]

**Comment by ix5** [comment]
Hi @milesmcc, while the API is free to use and not subject to any usage limits (provided on best-effort basis), you would probably have more success by using the underlying [geo_extractor](https://github.com/conflict-investigations/osint-geo-extractor/) library.

**Comment by milesmcc** [comment]
Thanks! Good to know. Tbh I'm not sure we will still implement this — it's very specific to the work we support in Ukraine, and less applicable to other investigations. But I'm not sure.
