### ISSUE TITLE
Cards on map view should have uniformly rounded corners

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#325]
Currently, the bottom of the cards seems to be cut off more sharply than the top.
<img width="367" alt="Screen Shot 2022-10-16 at 00 05 16" src="https://user-images.githubusercontent.com/100018299/196022981-bf67a708-f3cf-49ee-a421-d9d14095bf5e.png">

**Comment by noah-schechter** [comment]
If this was intentional I defer to you on the design choice, I just want to call your attention to it in case it wasn't.

**Comment by noah-schechter** [comment]
<img width="1255" alt="Screen Shot 2022-10-16 at 00 20 47" src="https://user-images.githubusercontent.com/100018299/196023491-c3970d3e-0724-4c8d-8589-bc98dadca912.png">

**Comment by milesmcc** [comment]
Longstanding isuse
