### ISSUE TITLE
Fix logo design on login page

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#331]
<img width="664" alt="Screen Shot 2022-10-16 at 23 49 45" src="https://user-images.githubusercontent.com/100018299/196108040-e1c6a263-adfe-4a08-b479-38f6637bd947.png">

**Comment by milesmcc** [comment]
Ugh yeah this is a Safari thing. It relates to how the Elixir autoformatter handles HTML code. I'll prowl around for a fix.

**Comment by noah-schechter** [comment]
Also a good reminder for me to test on Chrome too.
