### ISSUE TITLE
Rules inconsistency

### ISSUE THREAD

**Issue by epicfaace** [atlosdotorg/atlos#332]
Are contributions licensed under CC, GFDL, or both? See https://github.com/atlosdotorg/atlos/blob/main/policy/RULES.md#intellectual-property and https://github.com/atlosdotorg/atlos/blob/main/policy/TERMS_OF_USE.md#6-licensing-of-content

**Comment by noah-schechter** [comment]
Thanks for pointing this out. The rules and our content licensing model are both remnants of our older community-driven vision for Atlos; now that we’re focusing more on organizational partnerships, we may remove the rules and content licensing requirements entirely.

Anyway, thanks for bringing up inconsistency. Our intention is that contributions are licensed under both CC BY 4.0 and GFDL. Of course, it’s also worth noting that this only applies to contributions on the Atlos platform, which are governed by the [Rules](https://github.com/atlosdotorg/atlos/blob/main/policy/RULES.md) and [Terms of Use](https://github.com/atlosdotorg/atlos/blob/main/policy/TERMS_OF_USE.md). Our codebase is licensed under GPLv3.0.

**Comment by milesmcc** [comment]
Leaving open as we figure out our plan for our ToS and Rules going forward...

**Comment by milesmcc** [comment]
Resolved (no more rules)
