### ISSUE TITLE
Add local setup / development guide

### ISSUE THREAD

**Issue by milesmcc** [atlosdotorg/atlos#333]
Right now, I'm the only real contributor to the Atlos platform. Unless I create a local development guide, it'll stay that way. @epicfaace — thank you for the reminder here yesterday.

**Comment by noah-schechter** [comment]
I believe you put something together here: https://github.com/atlosdotorg/atlos/blob/main/platform/README.md. @milesmcc Closing this one; feel free to open it again if you feel there's something missing.
