### ISSUE TITLE
Hiding updates should remove profile picture from attribute display panel

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#371]
I know this one is hard; certainly not a priority, but I think we should track it nonetheless.

Right now, if I hide a user's edit to attributes from the feed, their profile picture still displays next to the attribute.

**Comment by milesmcc** [comment]
Not hard :)
<img width="601" alt="image" src="https://user-images.githubusercontent.com/3037552/200075762-2290c6a6-f866-489d-9413-84fc641900e1.png">
