### ISSUE TITLE
Change 'Everything' icon to Hero Icons 'arrow-trending-up'

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#390]
A suggestion, open to discussion here.

**Comment by milesmcc** [comment]
This one might look a bit strange 
<img width="150" alt="image" src="https://user-images.githubusercontent.com/3037552/203423301-c0f3bdbc-78e7-4e4d-ad4e-c4887b7ffe32.png">

**Comment by milesmcc** [comment]
What about `users`:

<img width="135" alt="image" src="https://user-images.githubusercontent.com/3037552/203423880-f4b1f89a-43a7-4129-a2ec-9cde6d023e26.png">

**Comment by milesmcc** [comment]
Actually this makes more sense:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/3037552/203424044-2f920e0f-7251-473c-8ccc-e5e94bee3765.png">
