### ISSUE TITLE
Dashboard 'Queue' display cuts off some titles

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#393]
This may be because of the large assortment of different statuses we have on staging, but there's an interesting display quirk happening in the queue/stats section of the Dashboard.
<img width="414" alt="Screen Shot 2022-11-19 at 21 50 41" src="https://user-images.githubusercontent.com/100018299/202888093-fe7949b8-7b62-4fa3-8d84-66ee9cfae432.png">

**Comment by milesmcc** [comment]
So that title is actually interesting — it’s blank because it’s empty! I guess on staging we have some incidents without a status (probably from the very early days).
