### ISSUE TITLE
Link display options

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#401]
I really like the hyperlinked link displayed under each piece of media. It minimizes the number of clicks it takes to open a source and feels like it belongs—I'm a big fan. That being said, it does add a lot of text that doesn't communicate meaningful information.

I'm wondering whether an arrow next to the social icon might accomplish the same thing, while limiting the amount of text we display? I tried this out in Figma and couldn't come up with something I liked but wanted to pass this by you before we deploy the link display on staging.

**Comment by milesmcc** [comment]
Discussed, keeping link (for CMD+F)
