### ISSUE TITLE
Metadata icons should be of uniform size

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#403]
It looks like they're scaled differently here. 
<img width="343" alt="Screen Shot 2022-11-28 at 17 25 28" src="https://user-images.githubusercontent.com/100018299/204415609-252dacc6-4484-423c-b91f-64fd6cd42b4b.png">

**Comment by milesmcc** [comment]
Should be fixed — reopen if not
<img width="414" alt="image" src="https://user-images.githubusercontent.com/3037552/204927264-c1290b0c-e52b-410f-bb07-3850f8ac5bbc.png">
