### ISSUE TITLE
Should 'Quick Access' always display 4 incidents?

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#411]
I'm not sure what the expected behavior is here, but I'm only seeing three right now. 

If that's expected, should we try to always display four incidents? 
If that's not expected, I'll change this to a bug.

<img width="1440" alt="Screen Shot 2022-12-01 at 10 34 51" src="https://user-images.githubusercontent.com/100018299/205133117-7cb2a920-2c00-4754-bbe6-01e93551c2dd.png">

**Comment by milesmcc** [comment]
It could be that in the near term you've only edited/had three incidents? What happens if you leave a comment on another? We could always just backfill from other `Unclaimed` incidents.
