### ISSUE TITLE
Should project codes (ie., CIV) be unique to each project?

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#447]
I think we should require each project to have a unique identifier to keep things more organized. I understand that not requiring a unique ID wouldn't risk creating duplicates, because the slug itself is always unique, I think it would be best to not duplicate identifiers.

**Comment by milesmcc** [comment]
I think we discussed this and decided that we shouldn’t require them to be unique, since there might be two separate users on self service Atlos that want to use `CIV` and it’s weird if we don’t let them do that.

**Comment by noah-schechter** [comment]
That makes sense, totally forgot about that conversation. Is it worth requiring each user's owned projects to have different codes?

**Comment by milesmcc** [comment]
We said no because then it could create issues if you're invited to a new project as an owner that has the same code as a project you're already a part of. But perhaps we add a warning?
