### ISSUE TITLE
Pressing 'enter' should clear comment prompt

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#454]
Not a big one—I'm mainly adding this to track it. Right now, pressing 'enter' to skip to a new line doesn't clear the 'Add a comment...' prompt; only typing does. I'm thinking that any key press should clear the prompt. Adding this to backlog.

**Comment by noah-schechter** [comment]
Not a deployment blocker.

**Comment by milesmcc** [comment]
Kind of unfixable without herculean effort because that logic is provided by a library we use.
