### ISSUE TITLE
Attempting to bulk export empty search results leads to Error 500

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#462]

**Comment by noah-schechter** [comment]
Not a deployment blocker.

**Comment by milesmcc** [comment]
Can't replicate?

**Comment by noah-schechter** [comment]
Sorry my wording was unclear here—this isn't a huge problem but if a user clicks 'export' after a search returns no results, they'll see an Error 500.

**Comment by milesmcc** [comment]
Ah got it. Not a deployment blocker but should definitely fix.
