### ISSUE TITLE
Incidents with projects should appear with the project's color on global map

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#480]
So users can easily distinguish different projects on the map. I don't think our current color-coding on the map adds too much value, so I think this is a helpful use of color.

**Comment by milesmcc** [comment]
Added for both global and project-specific map.

**Comment by noah-schechter** [comment]
Thanks! I really like the default color on the production map right now (top image); could we change the default back to the old one? Or is it not bright enough for the map?
<img width="95" alt="Screenshot 2023-01-30 at 10 53 29 AM" src="https://user-images.githubusercontent.com/100018299/215568852-8c9fb9b4-4928-46e5-95ba-b51a3a20b34f.png">
<img width="68" alt="Screenshot 2023-01-30 at 10 53 38 AM" src="https://user-images.githubusercontent.com/100018299/215568855-684ebacb-4889-4fa6-a2e3-cbffe6beeeea.png">

**Comment by milesmcc** [comment]
Changed back, deploying now
