### ISSUE TITLE
Consider making incident page's map pane curved

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#483]
Right now, the map pane on the incident page is squared off on the bottom. If this is intentional, feel free to close this issue—I just wanted to make sure this wasn't an accidental regression.
<img width="401" alt="Screenshot 2023-01-30 at 19 54 48" src="https://user-images.githubusercontent.com/100018299/215659405-fbf1e984-f032-4a25-bf2b-b63767e7aa7f.png">

**Comment by milesmcc** [comment]
I think this is an accidental regression

**Comment by noah-schechter** [comment]
Ok I'll leave the issue open then.
