### ISSUE TITLE
Broad custom attribute UI thoughts

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#485]
First of all—custom attributes look fantastic! I know most of the work was under the hood here but the UI is also really nice and really easy to use. Really awesome work here.

In broad terms, I want to think about how to make custom attributes feel a little more firm, stable, and deeply-rooted. I guess you could say the strategy is to add a bit of friction to the attribute creation and editing process so it feels like the significant, data-altering process that it is. The process should still be easy and AirTable-like, but it should still have the gravity of editing an underlying data model. 

I think there are several concrete steps we can take to make this happen; I'll spin these out into standalone issues once we come to decisions on each:
1. Don't permit creation of new attributes or updates to existing ones until all attributes are internally logical: All multi- and single-select attributes should be required to have at least one option and all attributes need a title. I
2. [I'm not sure where I stand on this one but curious to hear what you think] Add an edit (pencil) button to attributes in the Manage pane so users have to choose to edit and save changes to each attribute. This might clutter things but could also add the gravity/friction I mentioned above.
3. Add documentation on the Manage page to explain how to add attributes. There's a lot of horizontal space we could theoretically make use of next to the Attribute management pane. We can also create a separate documentation page, but I think it would be important to include in the platform too.

**Comment by noah-schechter** [comment]
This is a few steps too far but the GitHub "Danger Zone"/"Are you sure you want to do this"/"Type repo name here" feels like the type of gravitas from which this part of the UI would benefit

**Comment by milesmcc** [comment]
Going to close this since I *hope* the new UI resolves some of this, but feel free to reopen as you see fit.

**Comment by noah-schechter** [comment]
Yes new UI addresses this really nicely, thank you!
