### ISSUE TITLE
Consider removing date as a core attributes

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#493]
I'm considering whether we should require date as a core attribute. It certainly makes sense as a _default_ attribute, but in the pursuit of maximum flexibility I'm not sure it makes sense to require this? Unless it's necessary to make table view look decent.

**Comment by milesmcc** [comment]
If we want to support timeline views/more deeply integrate date into the map, I think we should lean towards keeping it (if something isn't a custom attribute, I think it makes it a lot harder to build features based on it). But if we aren't interested in building in features that rely on date, then I think it makes sense to remove it as a core attribute.

**Comment by noah-schechter** [comment]
Hmm ok I think we keep date as a core attribute then.

**Comment by noah-schechter** [comment]
Reopening this because I've realized that having two or more date attributes is quite weird. I think that we could take several approaches here:
1. Close the door on timeline views and just make date a custom attribute
2. Make core attribute's descriptions editable so that people can customize their use of the Date attribute while it remains core.
3. Prevent people from creating additional date-based attributes. This is needlessly restrictive; I don't think we should take this approach.

Perhaps we take approach #2. It feels like this will let people customize their use of the Date attribute without having to add a second Date field to every incident. This is certainly not a deploy blocker but something I do think we should think through thoroughly.
