### ISSUE TITLE
Consider collapsing Attributes pane

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#495]
I'm thinking about the best way to present a unified view of a Project's data model. My thinking is that the data model management pane should mirror, as closely as possible, the incident page. On the incident page, and even in general editor use of the platform, there's no difference between core and project attributes. I think the management pane should reflect that.

To that end, I think we should collapse the two panes we have now ("Project Attributes" and "Core Attributes") into a single pane called "Project Attributes" where the core attributes are listed above non-core attributes and just have a second flag (`Core`, for example) indicating they can't be edited.

**Comment by milesmcc** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/3037552/221479723-f51c42ea-eb54-40c1-8c58-799bbf4e9436.png">
