### ISSUE TITLE
Consider changing copy and visuals of feed updates regarding deleted attributes

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#497]
I think we should specialize our handling of deleted attributes in two ways:
1) Indicate that an update regarding a deleted attribute refers to a deleted attribute, as opposed to a broader, generic 'Unknown attribute.'

That would editing, for example
> updated [Unknown Attribute] 19 minutes ago 

to 
> updated a deleted attribute 19 minutes ago

2) The replacement for actual change tracking, the _Change is unavailable_ graphic I attached below, isn't really necessary. We can just display the above line of text.
<img width="810" alt="Screenshot 2023-02-25 at 17 08 27" src="https://user-images.githubusercontent.com/100018299/221386963-75a3b7de-d8bc-4c18-bd15-cb7df06969b7.png">

**Comment by milesmcc** [comment]
This is also what you see when you change an incident's project, so what about this: 
<img width="681" alt="image" src="https://user-images.githubusercontent.com/3037552/221716224-6aab9a74-78ca-4a1d-b7a7-2286e06a1997.png">

And when there's an explanation, we only show the explanation:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/3037552/221716265-e231b738-5cfc-45f6-ad57-b36895207c57.png">

**Comment by milesmcc** [comment]
Closing since I think this resolves the issue, but reopen as you see fit.

**Comment by noah-schechter** [comment]
This looks great; thank you
