### ISSUE TITLE
Consider restricting use of red as a project color

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#498]
Red is already used prominently to communicate graphic violence, so it's somewhat overwhelming and confusing to look at a red project on table view. Perhaps we don't include it as a permitted color? 

<img width="1329" alt="Screenshot 2023-02-25 at 17 17 52" src="https://user-images.githubusercontent.com/100018299/221387071-c3a0fdca-cb60-412b-aa4d-5b4951f7036b.png">

**Comment by milesmcc** [comment]
Makes sense. Part of me feels weird restricting them in this way, but it makes sense.

**Comment by noah-schechter** [comment]
Yeah I understand the hesitation here—it's a weird feeling restricting something like this. That being said, because we're starting from a point where we had already curated colors, I feel less uncomfortable with further curating them to better complement the UI.
