### ISSUE TITLE
Consider modifying project creation flow

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#499]
I think we should think about our need to communicate a few concepts to users during the project creation flow:
1) **Projects are highly configurable.** While it might be obvious that they can be managed in the Manage pane, I wonder if we should direct creators of new projects to this pane so that they can, for example, write a project description and edit the data model? Alternatively, users who need these tools will surely find them more organically. 

2) **Table view is project-specific.** Is this something we need to explicitly communicate anywhere? I imagine that some folks working on one project at a time won't bother to filter their view and will be stuck with limited attributes. Is a little UI nudge (down the road, of course) the solution here?

3) **Data modeling is hard and should be done at the beginning of a project.** This is a more opinionated design choice, but I wonder what steps we can take to help investigators choose a good data model at the beginning of a project. This encompasses two parts:
    a. How can we help users design robust models? I think this is mostly a question of good external documentation (on a separate   part of our marketing site, for example). Alternatively, we have space to the right of the Manage interface for documentation if we're willing to clutter the screen a little more. 
    b. How can we help users design their models early? Perhaps we answer this question by directing users to the Manage pane upon project creation. Maybe we even specifically send them to the Attribute part of the page. A UI nudge could work here too. Maybe we prompt an owner adding an incident to a project with default attributes to head to the Manage pane to customize attributes?

**Comment by milesmcc** [comment]
I agree with all these considerations; I also don't know to what extent we need to modify the project creation flow to achieve them. On 1, I think it makes sense to redirect people to the manage page when a new project is created, so I went ahead and made that change.

On 2, we currently show this at the bottom of the table when the query is not filtered to a particular project: 
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/3037552/221716706-5024d836-b529-4f66-bee2-417ef22d6e3a.png">

Perhaps this should be more prominent; open to ideas here. I want to make sure we don't clutter table view.

On 3, we can certainly put some documentation there. We currently show this message when they have the default schema:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/3037552/221717146-d98de5d3-d573-471a-aa4b-89e9336040a4.png">

Perhaps we can put relevant documentation here?

**Comment by noah-schechter** [comment]
Thanks for redirecting people to the manage page; I think that's a great choice.

On 2—the new pagination bar is great and I think it's sufficiently prominent. 

On 3—I'll spin out a new thread to create data model documentation/prompting. This will require some more thinking/research.
