### ISSUE TITLE
Make "We've provided some default suggested attributes for this project.." warning dismissible 

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#501]
Sorry this is a small one that might be really annoying to implement—as important as the "We've provided some default suggested attributes for this project. You can edit these attributes, or add new ones" warning is, I think users should also be able to dismiss it. If they want to stick with the default attributes, we shouldn't continue to push them to change the data model. What do you think about adding a little 'x' in the corner of the warning that is remembered for each user?

**Comment by milesmcc** [comment]
Yeah, this is a tricky one to implement, and the complexity might outweigh the benefits. One argument for keeping the message there so long as they stick with the defaults is that if they come back one day and want to customize, they can still access the documentation.
