### ISSUE TITLE
Update New Incident page to reflect recent changes to core attributes

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#502]
Right now, the New Incident page still displays the pre-custom attribute defaults. Ideally, we should display all core attributes on the New Incident page, and once the project is set, the Additional Attributes dropdown would give users access to the the custom attributes for the given project.

**Comment by noah-schechter** [comment]
Also, I think the Project field should be the first field on the New Incident page. My thinking here is that this will help anchor the user in the proper project, which is especially necessary because the New Incident page is global and not visually distinguishable for each project.

**Comment by milesmcc** [comment]
This is in progress locally; a bit tricky. Agree re: putting project first. Maybe we can even split it out into separate panels to make it feel more robust.
