### ISSUE TITLE
Switch from alternate views back to map view disrupts alignment of search bar

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#504]
Note the alignment of Status, Project, and Sort.
<img src=https://user-images.githubusercontent.com/100018299/223001936-44ec74c0-6190-4370-9625-4cd6347a5505.mov>

**Comment by milesmcc** [comment]
This is such a weird bug — almost feels like a browser bug!

**Comment by noah-schechter** [comment]
Will try on Chrome (Replicated across multiple devices on Safari)

**Comment by milesmcc** [comment]
I can replicate in Safari but not in Chrome. This is funny — this is 100% a Safari bug, probably only surfacing now because we bumped from Phoenix 1.6 to 1.7. We should fix, but... will need to figure out the best way how. Can do tonight I think.

**Comment by noah-schechter** [comment]
Great thank you!
