### ISSUE TITLE
Show total number of results for each search

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#505]
[Not a deploy blocker] I'm not sure if this is possible, but if we already have this info, could we show "Showing 1 to 51 of 143 incidents" instead of "Showing results 1 to 51"? I think this would be a helpful data point when people are navigating search results.

**Comment by milesmcc** [comment]
We used to have it but then I removed it because it made loading/searching really slow unfortunately (have to count a bunch of results each time they load the page)
