### ISSUE TITLE
Project-selection dropdown should close after selection

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#508]
Right now, the project-selection dropdown reopens even after a user has selected a project:

https://user-images.githubusercontent.com/100018299/223015968-4b9c1eb7-917d-42e8-a29c-3e506016f00f.mov

**Comment by milesmcc** [comment]
I agree. I think this is a problem with all our dropdowns, right? I don't know if this should block the deploy

**Comment by milesmcc** [comment]
I agree we should fix but this might be a longstanding issue
