### ISSUE TITLE
Archived attributes shouldn't be displayed on incident cards

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#511]
This may just be a migration issue, but we currently display attributes that have been archived (because those attributes exist in an incident's current project) on incident's cards:
<img width="429" alt="Screenshot 2023-03-05 at 8 13 32 PM" src="https://user-images.githubusercontent.com/100018299/223018119-f2e064d7-a31a-48d3-9888-85565f7a5bc8.png">
<img width="1251" alt="Screenshot 2023-03-05 at 8 13 38 PM" src="https://user-images.githubusercontent.com/100018299/223018122-62683da7-2db4-40d4-944a-038ef22c0218.png">

**Comment by milesmcc** [comment]
Good catch

**Comment by milesmcc** [comment]
Should this be self-assigned?

**Comment by noah-schechter** [comment]
Nope not sure how that happened. Thanks for the fix here.
