### ISSUE TITLE
Mark notification as read button interaction feels slow

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#513]
This is, of course, incredibly minor. If this is caused by a communication with the server, feel free to close this. 

But, if this is just an animation or something handled entirely by the browser, I think we should increase the speed of the icon change.

https://user-images.githubusercontent.com/100018299/223021374-b1e7359b-9cff-4e52-b837-999e159ae6bc.mov

**Comment by milesmcc** [comment]
That's done on the server unfortunately. Ideally we would move it client side (or do optimistic client side rendering).
