### ISSUE TITLE
Should removed media still appear in the feed

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#514]
Should the update about a user adding media that has since been removed appear in the feed?

<img width="1468" alt="Screenshot 2023-03-05 at 8 49 52 PM" src="https://user-images.githubusercontent.com/100018299/223022017-a77a0598-bfd2-4024-b838-38eb1103436f.png">

**Comment by milesmcc** [comment]
I think it should — feed is a log of what happened; perhaps we should just also show the action of marking as removed in the feed as well (perhaps as part of the content archival revamp).

Feel free to reopen if you disagree.
