### ISSUE TITLE
Profile image shouldn't reappear after user bulk selects an incident

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#518]
Right now, profile images briefly appear after a user selects an incident using the bulk selection tool. The profile image is quickly replaced by the filled-in blue checkbox, but it's a bit confusing. Could we ensure a selected incident is displayed with a filled-in checkbox without the intermediate profile image step?

https://user-images.githubusercontent.com/100018299/223558009-94cc0c88-766b-49a3-9dc8-afbcb4d975f5.mov

**Comment by milesmcc** [comment]
Fixed!
