### ISSUE TITLE
Consider exiting user out of bulk selection tool after applying a change

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#523]
This could go either way, but I think it makes sense to exit users out of the bulk selection tool once they've applied a change; it feels like a sufficiently assertive way of communicating that the change was successful. Otherwise, users might be slightly confused as to whether the change went through. 

(This is a tradeoff—it makes making multiple changes to the same set of incidents more annoying. I think that's a reasonable tradeoff.)

**Comment by milesmcc** [comment]
I'm less sure — I feel like applying multiple changes in a row would be a common thing to do, and deselecting everything after each action would get super annoying. Do you think the notification provides insufficient feedback?
