### ISSUE TITLE
Handling of profiles in Members pane appears to change based on bio size

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#531]
Note the height of the profile image and grey line at the bottom of the two leftmost cards.
<img width="1279" alt="Screenshot 2023-03-13 at 3 12 54 PM" src="https://user-images.githubusercontent.com/100018299/224844717-e9b25f77-e875-4187-8eb4-4c55ab33742e.png">

**Comment by noah-schechter** [comment]
Ok rethinking this and I think we should just standardize bio height, either by giving everyone two lines or by displaying only the first line of each bio—the page of cards with varying dimensions feels a bit off.

**Comment by milesmcc** [comment]
Hmm, I'm not sure — I feel like the second one looks better?

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/3037552/225104491-fcc51d3f-2b47-4d4f-9e2c-0ebe1cfa1a41.png">
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/3037552/225104611-663579fc-c596-4d84-8d62-46e75ecc58c4.png">

**Comment by noah-schechter** [comment]
I defer to you here but I wonder if cutting everyone off at one line would be best?

**Comment by noah-schechter** [comment]
Ok now that we've update the way we display Members, we have a different version of the same problem: 
<img width="1311" alt="Screenshot 2023-12-19 at 1 18 08 AM" src="https://github.com/atlosdotorg/atlos/assets/100018299/37bc603f-d427-48e3-89b8-31a094a9c150">

It looks like long bios:
- Compress profile images and cause the associated username to be misaligned
- Break up other text (like column titles) onto two lines unecesssarily
- Cause the Members and invites tables to take have different widths

If we need to, I think it's totally fine to truncate bios at a certain character limit and add an ellipsis.

**Comment by milesmcc** [comment]
I'll go one step further and say there's probably no need for bios here.

**Comment by noah-schechter** [comment]
I think removing bios was the right call, but it's now a bit too snug for the role chips:
<img width="902" alt="Screenshot 2023-12-19 at 11 32 31 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/8ac3e9f7-805e-4cb1-af0a-25d800773e24">
