### ISSUE TITLE
Remove 'Unset' option from search filters

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#532]
I think these are a bit confusing just because users are unable to leave these blank—they can never be unset.

<img width="384" alt="Screenshot 2023-03-13 at 3 16 43 PM" src="https://user-images.githubusercontent.com/100018299/224845188-ca7f70ca-d7e8-4190-a745-d91b8700cb4e.png">
<img width="421" alt="Screenshot 2023-03-13 at 3 16 50 PM" src="https://user-images.githubusercontent.com/100018299/224845196-4a23ceed-08ae-484c-b4c1-82b04fd4d572.png">

**Comment by milesmcc** [comment]
But keep it for tags?

**Comment by noah-schechter** [comment]
For tags it's possible the value is unset, so there is a reason to keep it. But I'm not sure why someone would need to filter by incidents _without_ a tag—perhaps we remove it for tags too.

**Comment by milesmcc** [comment]
I think we should keep it for tags since people might want to find all the untagged incidents so that they can add tags. Current implementation (which is a bit more generalized) includes `[Unset]` when the attribute is not required, and excludes it when it is.
