### ISSUE TITLE
Users logged as Manager in the interface can't mark incidents as Completed

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#542]
Specifically, Managers can edit Completed incidents and change the status of Completed incidents, they just can't actually change the status of an incident to Completed.

**Comment by noah-schechter** [comment]
This is also an issue for Owners who didn't create the project.

**Comment by noah-schechter** [comment]
Looks like it also applies to merging incidents.

**Comment by milesmcc** [comment]
The issue was that it was using the old permissions system, so it just was checking whether the user was an admin or not.

**Comment by milesmcc** [comment]
Should be fixed now in all places. There were straggling areas which I forgot to move to the new perms system.
