### ISSUE TITLE
'Post update' button takes too long to activate following a change to a text attribute

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#563]
[Not a deploy blocker] Right now, it takes too long for the 'Post update' button to become pressable after a user edits a text attribute. I think I was able to circumvent this with the command + enter shortcut, in case that's helpful. It took noticeably longer than the same change on platform.atlos.org, so I think this is a regression.

**Comment by milesmcc** [comment]
Reduced it to 200 ms after typing stops — how's that?
