### ISSUE TITLE
Remove date as a custom attribute

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#564]
This one might be controversial, and if we remove it before ship we can always add it back, but I think including date as a custom attribute could make filtering really confusing. If a user has two dates in a project (the core and custom version of the attribute), it's not obvious which attribute they're filtering by in the incidents page.

I think that, until its requested, we should hold off on offering it as a custom attribute.

**Comment by milesmcc** [comment]
Sounds good
