### ISSUE TITLE
Change displayed date in Date filter to reflect European or universal standard

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#569]
While we let users pick the date off the calendar in the Date filter, the date is still displayed in the American format. Could we display as Day/Name of Month/Year (03/September/2023) or, if that's not possible, the European format of Day/Month/Year (03/09/2023)?

**Comment by milesmcc** [comment]
It's actually localized to your computer's current time, so Europeans should see the localization they're used to; this input is controlled by the system. I think it's possible to verify this by setting your computer's localization to something like Germany.
