### ISSUE TITLE
Previously created tags don't appear to be remembered across interface 

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#570]
Despite creating several tags on staging, I'm not seeing any I can choose from in the Tags filter. I think this reflects a broader problem with tags because I was seeing a similar problem at the incident level. 
<img width="404" alt="Screenshot 2023-03-16 at 12 40 17 PM" src="https://user-images.githubusercontent.com/100018299/225734868-a24dd44c-034b-482b-959b-c5811debac11.png">

**Comment by milesmcc** [comment]
At the incident level, you should only see tags that are part of that incident.
