### ISSUE TITLE
Links on Notifications page should open in same tab

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#579]
I know we decided a while back on opening external links in a new tab, but this behavior on internal links from the Notifications page feels a bit odd:

https://user-images.githubusercontent.com/100018299/226073919-9da18d5a-2437-4bf2-9812-392e94db5be7.mov

**Comment by milesmcc** [comment]
The real solution here is to not hijack the announcements feature for project add notifications; I think it's better to avoid the complexity of _sometimes_ rendering Markdown such that links open in a new tab, and _sometimes_ not doing that.
