### ISSUE TITLE
Resetting search filters shouldn't change the search view

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#590]
I wasn't expecting the reset button to change the search view; I think it should only impact filters. Open to discussion here—let me know what you think.

**Comment by milesmcc** [comment]
Idk — My interpretation is that reset resets everything?

**Comment by noah-schechter** [comment]
I think that filters are conceptually distinct from view. Search view is a global choice—my guess is that most investigators only use one type of view, regardless of their search, which is why we decided to 'remember' search view. On the other hand, filters are specific to each task. Reset makes life easier by enabling users to bulk reset filters, but my thinking is that this shouldn't extend to search view, because it's something that most investigators prefer to keep consistent across searches and tasks.

**Comment by noah-schechter** [comment]
Ah sorry for the confusion there
