### ISSUE TITLE
Try capturing webpage PDF as single page 

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#605]
Right now, it looks like we're capturing webpage PDFs as 8.5 x 11 pages. That's fine, and I understand PDFs are a fundamentally printed medium, but it would be great if we stored the PDF as a single page so that page breaks don't dramatically disrupt formatting and display.

**Comment by milesmcc** [comment]
There doesn't seem to be a good way to do it reliably, but see how the current version of staging performs. It should get most pages as a single PDF.
