### ISSUE TITLE
Consider displaying media instead of viewport screenshots on incident page when link is a social media site

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#608]
I know we discussed this and concluded that the viewport screenshot is the best way to consistently communicate what each piece of media is, but after actually interacting with the new interface, I think having the media available and (for videos) playable on the incident page itself is really important.

Perhaps for Twitter, Telegram, TikTok, and YouTube links, we display the media, and for all others, we display the viewport screenshot?

**Comment by milesmcc** [comment]
Since there could be multiple media, was the resolution from our convo that we wouldn't do this?

**Comment by milesmcc** [comment]
(Or was it that we would do the grid? I also want to highlight that people might want to archive the actual Telegram message or tweet, and not just the media, so perhaps the interface should reflect that?)
