### ISSUE TITLE
System doesn't identify or alert users to perceptual hash matches 

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#609]
I've tried adding the following links, each of which have a photo with the following perceptual hash
Link 1: https://twitter.com/teamzelensky/status/1564979991389130757?s=20
Link 2: https://twitter.com/ukrainiansquad/status/1564960992425115648?s=20
PHASH: 5SQ56XW5CJQ=

But I'm not getting any feedback in the interface. I'm not yet sure what the expected behavior is; what should I be seeing here?

**Comment by milesmcc** [comment]
Am I on the project? I don't see these links on staging

**Comment by milesmcc** [comment]
Locally, I see for these links: 
<img width="798" alt="image" src="https://user-images.githubusercontent.com/3037552/234725068-0fc6fa3a-869f-4ff1-8171-da7d18d75e94.png">

**Comment by milesmcc** [comment]
Note that they have to be in the same project

**Comment by milesmcc** [comment]
Seems to also be working for me on staging:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/3037552/234729094-c4deda55-4a99-4ab0-b970-1e7cbf13131c.png">

**Comment by noah-schechter** [comment]
Hmm ok I see it now. I think I probably just missed it. I think this is just user error on my part but it may be worth considering a more dramatic warning.
