### ISSUE TITLE
Explore directly archiving hosted PDFs

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#610]
When a user adds a link to a PDF, i.e. https://theprairieecologist.files.wordpress.com/2020/01/a-field-guide-to-roadside-wildflowers-at-full-speed_january2020-1.pdf, would it be possible to directly archive the PDF in addition to taking the screenshots and page archive?

**Comment by milesmcc** [comment]
Yes, deploying now.
