### ISSUE TITLE
Confirm Internet Archive is successfully archiving source links

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#615]
I've tried viewing several source links submitted at least 20 hours ago on Internet Archive, and I'm getting a "Wayback Machine has not archived that URL." warning for each link. 

Some examples:
- https://staging.atlos.org/incidents/RDCMFF/detail/3
- https://staging.atlos.org/incidents/RDCMFF/detail/2

**Comment by milesmcc** [comment]
We don't have Internet Archive setup on staging, but it's live for gap and for platform.

**Comment by milesmcc** [comment]
(Because I don't want to spam the internet archive with test URLs.)
