### ISSUE TITLE
Incident copy success message doesn't display markdown correctly

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#616]
I'm not sure what's happening here, but it looks like the Atlos bot message isn't displaying a properly formatted backlink to the original incident.

<img width="789" alt="Screenshot 2023-05-04 at 7 41 49 PM" src="https://user-images.githubusercontent.com/100018299/236352489-e2950970-1f85-4511-bd85-a7b7e65d092c.png">

**Comment by milesmcc** [comment]
The problem here is that incident is a seven-letter code; it must have been created when incidents were be seven letters (on staging). I don't think we have any of those incidents on platform or gap.
