### ISSUE TITLE
Prevent platform signups from using GAP usernames

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#627]
This is an extreme edge case but I think we should consider preventing platform.atlos.org users from signing up with usernames in use by Bellingcat affiliates. This should save us from headaches in the case of a future migration.

**Comment by milesmcc** [comment]
Best way is to register accounts with all their usernames.

**Comment by noah-schechter** [comment]
Ok all non-suspended users now have accounts on platform.
