### ISSUE TITLE
'Open image in new tab' overlay doesn't match radius of source material

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#635]
Ok this is so so so small but thought I'd flag this—the overlay on the 'Open image in new tab' overlay seems slightly misaligned:
<img width="307" alt="Screenshot 2023-05-14 at 9 33 36 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/fd069475-9a6e-467f-855a-9f8c9daeb80d">

<img width="396" alt="Screenshot 2023-05-14 at 9 33 44 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/ac4ab3eb-2378-4cdb-bbec-240635395ce8">

This is really only visible with dark media (a black image, for example).

**Comment by milesmcc** [comment]
Well this is absolutely unacceptable.
