### ISSUE TITLE
Copy edit to risk message

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#652]
I think we should change "If you're conducting a sensitive investigation, or are concerned about anonymity, we encourage you to sign up under a pseudonym and use a VPN.
[Learn more about our security & safety on Atlos →](https://github.com/atlosdotorg/atlos/blob/main/policy/RISK.md)" to ""If you're conducting a sensitive investigation or are concerned about anonymity, we encourage you to sign up under a pseudonym and use a VPN.
[Learn more about your security & safety on Atlos →](https://github.com/atlosdotorg/atlos/blob/main/policy/RISK.md)"

I removed a comma and changed "our safety" to "your safety".

**Comment by noah-schechter** [comment]
Also I propose changing "Using Atlos carries risk." to "Like all web platforms, using Atlos carries risk."

**Comment by milesmcc** [comment]
Temporarily removed the message.

**Comment by milesmcc** [comment]
I think this is resolved? Once we've moved to Azure and have released the risk model, we should reintroduce the message.
