### ISSUE TITLE
Consider moving Bulk Import to a new tab on the Project page

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#661]
I think it's a bit hard to find in Manage, and doesn't totally fit under the 'Settings' vibe that the Manage pane has right now. Obv this would still be visible only to owners.

**Comment by milesmcc** [comment]
My concern here is that we already have a ton of different tabs for owners — I worry it's getting really crowded. Also, I'm not sure how "prominent" we want to make this feature. Are there any tabs you think we could remove?

**Comment by noah-schechter** [comment]
Ok that's persuasive. Perhaps we could condense the Manage page a bit? There's a lot of horizontal space open; I wonder if we could make use of that? 

Agreed re: prominence; I do want to make sure folks can I find it if they're looking for it, though.

And I think all of the panes are necessary, so I don't think removing one is possible right now.

**Comment by milesmcc** [comment]
Tried to make it look slightly better (though still has some of the same core issues of being... just long). What do you think?

**Comment by noah-schechter** [comment]
Ok I really like this; I think it's a great solution. Could you make sure this separator line extends across the screen as it does above?

<img width="1310" alt="Screenshot 2023-06-01 at 3 38 30 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/221f96a2-1126-4708-bb28-603d4725323d">
