### ISSUE TITLE
Markdown renders all numbers at the beginning of text as a numbered list

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#664]
This is a silly issue, and I'm not sure if this is fixable. When a user adds input to a text field that begins with "2.", the content is displayed as a numbered list, beginning with "1." The content following the "1." is also indented, as if it is part of the list. 

https://github.com/atlosdotorg/atlos/assets/100018299/8c25e413-6362-4aa9-babc-9cd3f4758703

**Comment by milesmcc** [comment]
Not much we can easily do about this one.
