### ISSUE TITLE
Consider copy edits to CSV error messages

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#665]
[Not a deploy-blocker] Right now, the error message for blank-but-required attributes looks like this:
<img width="883" alt="Screenshot 2023-06-01 at 3 44 23 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/4af1d410-2da7-4d3e-9c8c-c48d7ce6f7bc">

I think we should make sure we match the formatting of the attribute names in the documentation, meaning we would change attr_description to `description` by 1) adding a badge and 2) removing the "attr_" prefix. 

For example, the updated message would like:
- **Row 1**
`description`: can't be blank.
`sensitive`: can't be blank.
`status`: can't be blank.

Longer term, we can add more friendly messages, but for now I just want to make sure the attribute naming system matches what the system expects.

**Comment by noah-schechter** [comment]
For example, later on we should fix present our own error message for internal errors like this one:
> Escape sequence started on line 338: [User-inputted text] Comments: did not terminate. Parsing will continue on line 339. Escape sequences are allowed to span up to 10 lines. This threshold avoids collecting the whole file into memory when an escape sequence does not terminate. You can change it using the escape_max_lines option: https://hexdocs.pm/csv/CSV.html#decode/2

**Comment by milesmcc** [comment]
<img width="933" alt="image" src="https://github.com/atlosdotorg/atlos/assets/3037552/5c9483d0-a251-4884-af19-6cae992e87c5">

**Comment by noah-schechter** [comment]
This looks great, thanks!
