### ISSUE TITLE
Archival disclaimer doesn't have sufficient margins on some source material modals

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#699]
I'm not sure what about this specific link is causing the problem, but our little disclaimer in the bottom left corner of the modal doesn't have sufficient margins here:

<img width="1092" alt="Screenshot 2023-06-27 at 4 39 16 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/4cedc372-e143-4761-93a6-203660becd2d">

**Comment by milesmcc** [comment]
The issue is that the title is very long, and it's pushing the disclaimer past the end of the modal. I made two changes to fix this. First, I made the left side scrollable. Second, I trimmed the title and URLs a bit more aggressively so that they're shorter.
