### ISSUE TITLE
Make bulk export file names informative

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#705]
I think it'd be nice to make bulk export file names more informative. When folks just export a whole project, perhaps we can include the project name in the CSV file name. When the data is the product of a more complex query, perhaps we include each search term and filter? Or just the date, time, and "Atlos Export"? Just thinking this would be a nice small quality of life improvement.

**Comment by milesmcc** [comment]
Filters are challenging; for now I've done this:

<img width="261" alt="image" src="https://github.com/atlosdotorg/atlos/assets/3037552/a922134c-810b-4ee4-9a5e-a130c2d49111">

Happy to revisit as necessary.
