### ISSUE TITLE
Add 'Time' attribute type 

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#712]
So that folks can format upload time, event time, and other time-based attributes consistently.

**Comment by milesmcc** [comment]
Just to confirm, this is date + time? (So, for example, `June 3 at 3:32pm`, rather than just `3:32pm`?)

**Comment by noah-schechter** [comment]
I'm not sure. Chris currently uses the default Date attribute and a separate, custom Time attribute that's just a text field. Do you think it would be more helpful to create a date + time type or to create only a Time type? If we want to add a date + time type, do we also need to offer date only? Or should we just convert the date type into date + time?

**Comment by milesmcc** [comment]
Perhaps the best thing to do here would be to do time + datetime.

**Comment by milesmcc** [comment]
Closed by 2929f990a75e6b5a9b024e8c8560934674fe51fa
