### ISSUE TITLE
Swap remove member button's icon and location

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#744]
The new Access page is reallllly nice but something really irks me about the red remove member button. I think there are three components here: the color is a bit intense, it shifts the settings button over in a way that messes up each row's settings button alignment, and the icon itself is a little funky.

Three proposals (some of which aren't mutually exclusive):
1. Change the color of the remove button to match the settings color. I found that a gray remove member button was a little more pleasant (this screenshot is just in the browser so I didn't match the color perfectly):
<img width="538" alt="Screenshot 2023-10-19 at 12 43 23 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/256a3115-392e-4458-ab28-b3a4266296b7">

2. Swap the order of settings and remove member buttons. This one is weird because the remove button doesn't feel like it should be interior to the settings button, but this would keep each settings button in one column, which is nice. 

3. Swap the remove button for a different icon entirely. Options include: 

`x-circle`
<img width="37" alt="Screenshot 2023-10-19 at 1 07 48 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/86b4b120-3e26-44cc-811f-4412b15597e6">

`x-mark`
<img width="32" alt="Screenshot 2023-10-19 at 1 07 54 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/3f9ee8cd-14e2-4b0a-8acc-b6951e7e1796">

`circle`
<img width="52" alt="Screenshot 2023-10-19 at 1 09 44 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/d3263f2a-1760-4c1e-abf1-59b1eda78296">

`minus-circle`
<img width="46" alt="Screenshot 2023-10-19 at 1 10 56 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/eb7886f0-f3a2-49d3-b7fc-ff54e6070be0">

**Comment by milesmcc** [comment]
I like minus circle, dark

**Comment by milesmcc** [comment]
(With order switched)
