### ISSUE TITLE
Change Atlos bot's profile image to Atlos logo 

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#745]
**Current:** 
The Atlos bot's profile image is a settings (gear) icon.

**Proposed:** 
Atlos bot's profile image should be the Atlos logo.

**Rationale:** 
Right now, if the Atlos bot makes sets an attribute (for example, during bulk import), then we see a gear icon next to an attribute value, which looks like it might be a settings button. To avoid confusion, I think we can just make the image the Atlos logo.

<img width="147" alt="Screenshot 2023-10-19 at 1 24 21 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/c431acb0-7aa5-4fa1-bd68-645bfcfa820b">

**Comment by milesmcc** [comment]
I don't think the Atlos logo would look good at this size. Can we use some other icon instead? Perhaps some kind of bot icon?

**Comment by milesmcc** [comment]
<img width="509" alt="image" src="https://github.com/atlosdotorg/atlos/assets/3037552/733239bb-fda0-4ef1-bea1-e297a2888953">
Here's what I came up with

**Comment by noah-schechter** [comment]
This looks great
