### ISSUE TITLE
Add language on pricing to onboarding flow 

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#750]
[Noah will write this at a later date]

**Comment by noah-schechter** [comment]
For pricing, let's add a new penultimate slide that reads:

**Start for free. When you're ready, choose from one of three tiers:**
⚡ **Free**—Start using Atlos for free today. You'll be able to edit a limited number of incidents per month and will have unlimited view access.

📈 **Pro**—Power users pay $20 per month for unlimited access to Atlos.

🏢 **Enterprise**—Teams of fewer than 17 pay $500 monthly for invoice billing and priority support. Larger teams pay $30 per person per month. 

<img width="470" alt="Screenshot 2023-12-27 at 8 31 53 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/fe01ade5-72b8-4a3c-bb54-eda78e8a949e">
(Note that the image doesn't have bold tier names; the text in this issue, not the image, is the source of truth for this ticket.)

**Comment by milesmcc** [comment]
<img width="588" alt="image" src="https://github.com/atlosdotorg/atlos/assets/3037552/df2fe906-ee3e-4d00-8fc9-4a45f34b669c">

How is this? I made a few small changes. Specifically, I changed "unlimited" to "full" as there will still be _some_ restrictions, just not restrictions that any reasonable investigation/user would encounter (people can't upload terabytes of data).

**Comment by noah-schechter** [comment]
For security language, I propose we add a slide after the safety slide that reads:

**We're also committed to security.**

🔒 We built Atlos with security top-of-mind and have undergone an independent security audit. 

🛟  We also recognize that all tools inherently carry risk. We recommend you don't upload material that could jeopardize people’s safety if made public.

🔗 Learn more about our approach to security in our risk model.

Image format: 
<img width="461" alt="Screenshot 2023-12-27 at 8 59 36 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/5ab0e72d-4712-4daf-8252-569ad23ed2e8">

Note that I'm not too worried about the impact of adding two slides to the onboarding flow on our churn rate because as far as I can tell, when people start onboarding, they always finish. The blocker is the initial email click, not the onboarding slides.

**Comment by noah-schechter** [comment]
> How is this? I made a few small changes. Specifically, I changed "unlimited" to "full" as there will still be _some_ restrictions, just not restrictions that any reasonable investigation/user would encounter (people can't upload terabytes of data).

This looks great.

**Comment by milesmcc** [comment]
![Uploading image.png…]()
