### ISSUE TITLE
Don't show notifications for hidden, deleted, or merged incidents 

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#774]
Right now we show the following message in lieu of updates about hidden, deleted, and merged incidents:

> You do not have permission to see this update. The incident may have been removed, you may have been removed from the project, or the update may have been hidden.

Ideally, both for ease of use and so that users don't know these notifications exist in the first place, we wouldn't show these notifications at all.

**Comment by milesmcc** [comment]
These notifications will now be marked as read and filtered out.
