### ISSUE TITLE
New incident modal lacks project dropdown

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#802]
**Repro**
1. Open the new incident modal by clicking **+**. I've been unable to reliably reproduce this bug and am logging it here for good measure. 

**Current** (Occasionally)
The new incident modal appears without the project dropdown:
<img width="658" alt="Screenshot 2023-12-06 at 6 39 17 PM" src="https://github.com/atlosdotorg/atlos/assets/100018299/5f763b04-243b-493c-a334-06563d91f74a">

**Exprected**
The new incident modal should include the project dropdown.

**Comment by milesmcc** [comment]
I've seen this happen too.

**Comment by milesmcc** [comment]
Likely fixed. Reopen if you spot it again.
