### ISSUE TITLE
Simplify notification system

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#803]
**Current**
Right now, there are two system for marking a notification as read: clicking the blue dot on the left and clicking the blue arrow on the right. This is redundant.

**Proposed**
Eliminate icons on the right and include only the blue dot on the left. If we think it's a valuable feature to mark a read notification as unread, add the blue circular arrow icon on the left of read notifications on hover.

**Comment by milesmcc** [comment]
Is the redundancy inherently a problem? I actually forgot that you could mark notifications as read by clicking on the blue dot. I think the current system is nice and usable.
