### ISSUE TITLE
Sync tooltips across UI

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#826]
**Current** 
Users don't know whether a given username will display a profile tooltip on hover.

 **Proposed** 
We should be consistent about when we display profile tooltips across the interface. 

@milesmcc What performance implications does this have?

**Comment by milesmcc** [comment]
Having more tooltips can just make the page slower, though not by a ton. I'm becoming increasingly convinced that tooltips are generally cumbersome and are only necessary when we don't display the username (e.g., next to attributes). When we do show the username, the only thing that tooltips do is show you the bio, and that's not particularly helpful imo.

So I propose we only show tooltips when we _don't_ show the username. That should roughly line up with currently platform behavior.
