### ISSUE TITLE
Remove Incident-level restrictions with duplicate functionality 

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#834]
**Current**
Atlos offers four incident-level restrictions, some of which offer near-duplicate functionality:
- Hiding an incident prevents editors and viewers from seeing or editing an incident. Hidden incidents appear in project managers' and owners' searches.
- Deleting an incident prevents editors and viewers from seeing or editing an incident. Deleted incidents do not appear in project managers' and owners' searches and are instead visible in the Deleted pane of the project, which is accessible to project owners and managers. 
- Freezing an incident prevents editors and viewers from editing it. 
- Marking an incident as Complete or Cancelled prevents editors and viewers from editing it and also indicates a change in the incident's position in the editorial workflow. 

**Proposed**
1. Hiding and Deleting have functionality that is sufficiently similar that Atlos doesn't need both. Deleting is a well-defined concept; I recommend we remove the Hiding feature. If necessary, we can rename deleting to indicate it hides media from users without elevated permissions.
2. The same is true for Freezing and marking an incident as Complete or Cancelled. The tradeoff here is larger than in 1, because changing an incident's status is meaningful independent of the freezing component. That said, Freezing is worth removing if we're looking to simplify permissions.

For context, here's Atlos' current permissions schema: https://docs.google.com/spreadsheets/d/1VnxaWqQGQcLBe4uy1QwYY2nkV50W7jeKHbESKsOFhpw/edit#gid=0

**Comment by milesmcc** [comment]
What should we do about incidents that are currently hidden? I do think that hiding serves a purpose — GAP, for example, used it to restrict access to extremely graphic content. If we do decide to get rid of it, we need to have a "safe" offramp for already hidden incidents (and I don't think deleting them is the right thing to do here).
