### ISSUE TITLE
Sync naming of minimizing/removing/restricting/freezing/archiving/deleting content across source material, incidents, and projects 

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#835]
The fact that this title carries any meaning is a problem. I'll use this sheet to propose an alternative naming schema: https://docs.google.com/spreadsheets/d/1VnxaWqQGQcLBe4uy1QwYY2nkV50W7jeKHbESKsOFhpw/edit#gid=0

**Comment by noah-schechter** [comment]
**Current**
Right now we have several types of similar operations that occur at the levels of project, incident, and source material, all with different names:
- Projects:
  - `Archiving` a project keeps its data visible to all members but editable by only managers and owners. Only managers and owners can archive a project.
 - Incidents:
   - In #834, I proposed deprecating removing and freezing.
   - `Deleting` an incident makes its data visible only to managers and owners; deleted incidents are not visible in platform searches. Only project managers and owners can delete incidents.
 - Source material: 
    - `Minimizing` source material keeps source material visible to all members but moves it to a separate part of the source material pane.
    - `Removing` source material makes its data visible only to managers and owners. Only project managers and owners can remove source material. 

**Proposed**
Assuming we also implement #834, the only change we need to make is renamed `Remove` to `Delete`. By renaming Remove, we communicate that the source material-level action is conceptually identical to the incident-level action.

One potential concern with this approach is that `Deleting` sounds destructive. While understandable, this shouldn't be a blocking concern about for two reasons:
- We can use tooltips (and users can use UI clues, like the existence of a Deleted page) to communicate that Deleted objects are still accessible to privileged users.
- We already made the decision to use the word "Delete" to communicate about a similar incident-level actions. 

I'm not proposing making any change to the `Archive` term at the project level. It is conceptually distinct from deleting because it doesn't change the visibility of data to unprivileged users. One option would be to rename it `Lock`, but I think I prefer `Archive`.

**Comment by milesmcc** [comment]
> Archiving a project keeps its data visible to all members but editable by only managers and owners. Only managers and owners can archive a project.

Managers and owners cannot edit data in archived projects.
