### ISSUE TITLE
Media upload (archival and manual upload) failing on platform 

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#846]
**Repro**
1. Navigate to an incident on platform or staging.
2. Click **Upload media**.
3. Paste in a link.

**Current**
The loading bar moves slowly and we see a platform error on AppSignal.

**Expected**
The link should be added an the user should be able to continue by clicking **Publish to Atlos**.

Note that this applies to link archival and manual upload.

**Comment by milesmcc** [comment]
Seems fixed?
