### ISSUE TITLE
Reconcile help center and platform licenses

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#851]
The help center Hextra template is MIT-licensed; we may need to flag that different components of the Atlos repo are licensed differently in the repo-wide license.

**Comment by milesmcc** [comment]
The template is MIT licensed, which is [GPL compatible](https://softwareengineering.stackexchange.com/questions/204410/how-are-gpl-compatible-licenses-like-mit-usable-in-gpl-programs-without-being-su). Once we pull it into Atlos, our particular copy (with our content, in our repo) will get subsumed and the full repo will still be GPL. IANAL but I am a FOSS licensing geek.
