### ISSUE TITLE
Add more robust documentation on best practices for database-level logging and permissions to aid self-hosting orgs

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#858]
**Current**
We've put a lot of work into optimizing our database (Postgres and S3) configurations for integrity but haven't documented this in a way that would aid an organization that's self-hosting Atlos.

**Proposed**
We should add a detailed description of our recommendations for database-level logging and permissions configurations to `self-hosting.md` in the help center.

**Comment by milesmcc** [comment]
We don't currently do database-level logging (apart from the point-in-time restore that Azure's managed DB makes available to us).

I'll add a note about S3 to self-hosting.
