### ISSUE TITLE
Add explanation of file structure of full export to help center

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#859]
**Current**
Right now, we don't have a great visual description of the (somewhat complex) file structure of full exports anywhere.

**Proposed**
Adding a diagram like the one below to the help center is the fastest way to explain this file structure.

![Screenshot 2024-01-03 at 7 42 43 PM](https://uploads.linear.app/c83828de-1d70-41e4-9e4d-daaab0a66584/aa07af2b-99cd-4998-88a0-d4374cbf46fd/8df3b9d4-071c-4802-ab6e-328daf127b9e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2M4MzgyOGRlLTFkNzAtNDFlNC05ZTRkLWRhYWFiMGE2NjU4NC9hYTA3YWYyYi05OWNkLTQ5OTgtODhhMC1kNDM3NGNiZjQ2ZmQvOGRmM2I5ZDQtMDcxYy00ODAyLWFiNmUtMzI4ZGFmMTI3YjllIiwiaWF0IjoxNzA0ODI5MjM4LCJleHAiOjMzMjc1Mzg5MjM4fQ.-Jz3ishOpblGunzs_G-36lMzT0Of1NACZ-nnwHQ0NcE "=120x")

**Comment by milesmcc** [comment]
Will this be redundant to the `README.md` file included in the export?

**Comment by noah-schechter** [comment]
Yes, and that's ok—I think that the `README.md` effectively serves as in-platform documentation. Just as many features are well-documented in the interface and are explained in the help center, I think it's ok to explain it in both locations. 

I think this is especially important because we want it to be possible to figure out what you're getting from a full export _before_ you run it, so that people don't run full exports unnecessarily. 

Unless you disagree with my logic above, I'll keep this assigned to me so that I can implement it.

**Comment by noah-schechter** [comment]
Ok I think that's fair. Then the question is what our policy is as to what goes where. 

To me, a reasonable answer is:
1. The platform needs to be usable without the docs. With the exception of API documentation (because developers expect it to be external), every feature should be comprehensible and discoverable without the docs. 
2. The docs, then, should mainly serve to a) help investigators understand features that they've seen in the platform but had questions about or b) help investigators discover existing features they need but haven't found in the platform. 
3. When they fit, explanations of behavior (like the README) should be in the platform, not in the docs, because 95% of users are never going to open the docs.
