### ISSUE TITLE
Make date attribute set to today's date by default

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#873]
**Current**
The date selector is currently displays the current date by default, but users still have to click on that date to confirm their choice.

**Expected**
If possible, setting the date to the current date should require no click on the date selector.

**Comment by milesmcc** [comment]
I don't think we should set it to today's date by default; that would then make it unclear when you're editing an attribute whether the value was already set to the current day, or if it was just the default date.
