### ISSUE TITLE
Include  comments from donor incident when copying an incident across projects

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#883]
**Current**
Right now, we copy attributes and source material from donor incidents when copying across projects.

**Proposed**
We should also copy comments. For commenting users who are in the donor project but not in the receiving project, we could just redact the username.

**Comment by milesmcc** [comment]
I don't think we should copy comments/updates; people might make a comment on an incident for one project and not expect it to be present in another project, regardless of whether their username is redacted. I think we should provide a link back to the original project, but I really think that copying comments/updates muddies the data boundary. What do you think?
