### ISSUE TITLE
Navigating back in browser history shows protected content if user has just logged out

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#895]
**Repro**
1. Log out of an Atlos account.
2. Navigate back one step in browser history.

**Current**
Atlos temporarily shows content that should only be visible to a logged-in user.

**Expected**
Atlos shouldn't show sensitive content and should immediately show the log-in flow again. 

(I've sent a video privately)

**Comment by noah-schechter** [comment]
This is not a regression btew

**Comment by milesmcc** [comment]
I think this is the browser just caching the previous page.
