### ISSUE TITLE
Downloading MFA backup codes shouldn't open new tab

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#906]
[Not a deployment blocker]

**Current**
On Safari, downloading MFA backup codes opens a new tab with a URL of `about:blank`.
On Chrome, the same occurs, but the tab automatically closes a moment later.

**Proposed**
Ideally, MFA backup code download behavior would mirror that of CSV export—Atlos doesn't open a new tab, it just downloads the codes to a .txt file.

**Comment by milesmcc** [comment]
Actually had to make CSV export behave this way to fix breaking the incidents page. Will explore longer term if there's a way to make the page close automatically.
