### ISSUE TITLE
Consider removing contents of comments from notification emails 

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#921]
**Current**
We show the contents of the comment in which a user was tagged in the email.

**Proposed**
We should consider not displaying the contents of the comment. Including the contents "leaks" investigative work off-platform. If a user's email is breached but they have MFA turned on for Atlos, an adversary could access sensitive information from an inbox while remaining locked out of Atlos. In other words, including the contents of comments in update emails increases the surface area of potentially-sensitive info.

**Comment by milesmcc** [comment]
Do we provide a link to the comment or note who made the comment?

**Comment by noah-schechter** [comment]
I think a link to the comment is fine; I think noting who made the comment is a bit of a gray area. I think saying "You were tagged in CIV-12345. Click below to continue the discussion." is fine. (Although a link does make phishing more believable, right?)
