### ISSUE TITLE
Move decorator editing window within attribute editing window

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#927]
**Current**
Users configure the decorators for each attribute in a separate part of the Manage page from where they configure the corresponding attributes. 

**Proposed**
I think users should configure decorators within the editing modal for the corresponding attribute. Is the issue here that that would crowd the modal?

**Comment by milesmcc** [comment]
There are four reasons why I didn't do this, three UX and one practical:

* I suspect users will often want to edit decorators in bulk; having to go individually into each attribute and re-specify attribute values feels like a pain. In my mind it makes sense to think about all the decorators together.
* I also think that it would indeed make the editor window crowded.
* Decorators should be a rarely used feature; to the extent possible, I think we should remove them from the regular user flow.
* It'd mean that we'd need to create popup modals for editing core attributes, which is a bit of a pain; it'd also require refactoring the Phoenix form, which would be annoying.

Closing for now but reopen if this explanation is not compelling and/or you feel strongly that it _needs_ to be in the attribute editor.
