### ISSUE TITLE
Change decorator info displayed for on Manage page

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#935]
**Current**
For each attribute with decorators enabled, we display the name of the attribute and the name of its decorator on the Manage page. In most cases, each decorator in a project will be identical across many attributes, so this information isn't incredibly helpful. 

**Proposed**
I'm not sure what information would be more helpful—perhaps we don't need to display anything? If we are going to display this data, I think a table is more appropriate because it maps neatly to the attributes table above (and I think a table is worth the information density tradeoff relative to the pills). 
<img width="871" alt="Screenshot 2024-03-03 at 1 22 54 AM" src="https://github.com/atlosdotorg/atlos/assets/100018299/4f8d24f9-db33-4d34-8b7a-b554962b3451">

**Comment by milesmcc** [comment]
Hmm — the goal here is to show you which attributes have decorators enabled; I feel like it's worth keeping only the pills? A table feels like too much
