### ISSUE TITLE
Make Additional Information dropdown on incident modal more prominent

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#939]
**Current**
Users have mentioned that they miss the additional information dropdown on the new incident modal, and that the extra click slows them down.

**Proposed**
We should consider either:
1. Removing the dropdown and collapsing all fields into a single form. 
2. Making the drop-down more prominent and making it more clear that it minimizes additional information.

**Comment by milesmcc** [comment]
![CleanShot 2024-03-17 at 13 45 50@2x](https://github.com/atlosdotorg/atlos/assets/3037552/fc00732b-abfb-4d96-b1a9-aa24ae1aa8bf)

How about something like this? I think that opening the dropdown always is untenable; if you have 100 different attributes, that will be hell. With only a few decorators it already gets unwieldy:

![CleanShot 2024-03-17 at 13 46 55@2x](https://github.com/atlosdotorg/atlos/assets/3037552/fd086e25-7670-4453-b41b-11bbf90b3c47)

**Comment by noah-schechter** [comment]
This is perfect, thanks.
