### ISSUE TITLE
Don't display whitespace at the end of decorator names

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#942]
**Current**
Contrary to our approach to project names and attribute names, we currently display the whitespace (if any exists) at the end of decorators' names. For instance, if the decorator is "Confidence ", we display this info as `Confidence : Alleged` on the Attributes pane.

**Proposed**
Instead, we should parse this whitespace the same way we do project names and attribute names; the name "Confidence " should be displayed as `Confidence: Alleged`.

**Comment by milesmcc** [comment]
Fixed by making it so that attributes don't allow leading or trailing whitespace. Existing attributes will be unaffected.
