### ISSUE TITLE
Remove Overview page from Data-only Viewer's project view

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#986]
**Current**
Right now, we display four tabs for Data-only Viewers: Overview, Map, Queue, and Members. 

**Proposed**
We should remove the Overview page, because it will never display any information for Data-only Viewers. It currently displays a **Load more** button, which when clicked just displays a blank page. This is especially confusing because it seems like the page is _supposed_ to display more information. The least confusing choice for Data-only Viewers is just to not display the page in the first place.

**Comment by milesmcc** [comment]
What about stats? We show stats to data-only viewers.
