### ISSUE TITLE
Consider changing Access page for Data-only Viewers

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#989]
**Current**
The Access page for a Data-only Viewer looks the same as it does for any other Viewer, except we only display the own user's name.

**Proposed**
This isn't strictly necessary, but it's a little odd that we present the Access page as if it is a list of users ("View and manage the users who have access to the project.") but don't actually display the list of users. Perhaps we can change that copy? Or maybe there's a better way to indicate that they're not the project's only member without showing them anyone else's info?

**Comment by milesmcc** [comment]
I propose "View and manage access to the project." plus, if you're a read-only viewer:

![CleanShot 2024-05-20 at 01 42 42@2x](https://github.com/atlosdotorg/atlos/assets/3037552/fdadeacf-00c2-48dd-883f-6d19067ab44d)
